### ISSUE TITLE
Cannot make pull requests

### ISSUE THREAD

**Issue by rainmaker2k** [icemobilelab/jobs#1]
The project can't be forked, which makes it impossible to make any pull requests. 

I think this can be fixed by adding something in the repository.

**Comment by yalamerde** [comment]
Quite unfair, isn't it? ;)

**Comment by ksatirli** [comment]
Thanks for pointing this out @rainmaker2k and for following it up @yalamerde! We've neglected this one, a bit.

You should now be able to fork the repo to your liking. Show us some fun stuff!

- Kerim
